apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: boutique-cert
  namespace: istio-system
spec:
  secretName: boutique-cert
  dnsNames:
    - "boutique.c0.kube8.ga"
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  commonName: "boutique.c0.kube8.ga"
